### PR TITLE
Removed unecessary components and modified the UI a bit

### PR DESCRIPTION
**Pull request by leedagr8**
Removed some unnecessary Components from page and changed the layout a tad bit.

This is how the new UX would look.

Let me know what you think

image

### CODE REVIEW

**Comment by Nashluffy** [comment]
@leedagr8 I'd rather keep stuff (even if it's random shit) for now, it looks more complete then stuff waiting to be filled in. We can remove things as we progress and have stuff to take its place. 

For example, I was thinking instead of a table at the bottom, we would have a log of effects/actions applied on tracks. But for the time being, leave the table in as a place holder. That way we can have a rough outline of the website.

It looks kind of empty in the screenshot. Up to you and @pressure101 though, I'm ok with it if y'all are.

**Comment by pressure101** [comment]
So, I discussed a little with Leon. Sounds like I will focus on the landing page, and Leon will start working on the home page with audio clip manipulation. I think we are on the same page to leave some aspects of the site on the home page for now with the presentation coming up quickly.

**Comment by leedagr8** [comment]
image
Updated user page. let me know what you guys think 
@Nashluffy 
@pressure101 
@twantheswan

**Comment by Nashluffy** [comment]
@leedagr8 it looks great! I'm gonna resolve the conflicts and merge it in

**Pull request merged**
